-- Esquema de MotoVecino en Postgres. Corre en cada arranque (db.init): todo es
-- "IF NOT EXISTS" / "OR REPLACE", así que repetirlo no cambia nada.
--
-- Las fechas siguen guardándose como TEXTO en UTC ('YYYY-MM-DD HH:MM:SS'),
-- igual que en SQLite: así las apps, los respaldos viejos y las comparaciones
-- de texto ("cooldown_until <= ahora") se comportan exactamente igual.
-- Columnas nuevas: agregarlas abajo con ALTER TABLE ... ADD COLUMN IF NOT EXISTS.

-- ---------- Funciones de fecha con el mismo comportamiento que SQLite ----------
-- El código sigue escribiendo datetime('now', '-6 hours'), date(x, 'start of
-- month'), julianday(x)...; db.js cambia datetime( → sl_datetime( y
-- date( → sl_date( (date() choca con el tipo date de Postgres).

CREATE OR REPLACE FUNCTION sl_ts(t text, mods text[]) RETURNS timestamp
LANGUAGE plpgsql STABLE AS $$
DECLARE
  ts timestamp;
  m text;
BEGIN
  IF t IS NULL THEN RETURN NULL; END IF;
  IF lower(t) = 'now' THEN
    ts := date_trunc('second', now() AT TIME ZONE 'UTC');
  ELSE
    BEGIN
      ts := t::timestamp;
    EXCEPTION WHEN others THEN
      RETURN NULL; -- SQLite regresa NULL con una fecha que no entiende
    END;
  END IF;
  FOREACH m IN ARRAY coalesce(mods, '{}') LOOP
    m := lower(trim(m));
    IF m = 'start of month' THEN
      ts := date_trunc('month', ts);
    ELSIF m = 'start of day' THEN
      ts := date_trunc('day', ts);
    ELSIF m = 'start of year' THEN
      ts := date_trunc('year', ts);
    ELSIF m ~ '^weekday [0-6]$' THEN
      -- Avanza al siguiente día con ese número (0 = domingo); si ya lo es, se queda.
      ts := ts + ((substr(m, 9)::int - extract(dow FROM ts)::int + 7) % 7) * interval '1 day';
    ELSIF m ~ '^[+-]?[0-9]+(\.[0-9]+)? *(second|minute|hour|day|month|year)s?$' THEN
      ts := ts + m::interval;
    ELSE
      RETURN NULL;
    END IF;
  END LOOP;
  RETURN ts;
END $$;

CREATE OR REPLACE FUNCTION sl_datetime(t text, VARIADIC mods text[] DEFAULT '{}') RETURNS text
LANGUAGE sql STABLE AS $$ SELECT to_char(sl_ts(t, mods), 'YYYY-MM-DD HH24:MI:SS') $$;

CREATE OR REPLACE FUNCTION sl_date(t text, VARIADIC mods text[] DEFAULT '{}') RETURNS text
LANGUAGE sql STABLE AS $$ SELECT to_char(sl_ts(t, mods), 'YYYY-MM-DD') $$;

CREATE OR REPLACE FUNCTION julianday(t text) RETURNS double precision
LANGUAGE sql STABLE AS $$ SELECT extract(epoch FROM sl_ts(t, '{}'))::double precision / 86400 + 2440587.5 $$;

-- ROUND(real, 2) existe en SQLite; en Postgres solo para numeric.
CREATE OR REPLACE FUNCTION round(double precision, integer) RETURNS double precision
LANGUAGE sql IMMUTABLE AS $$ SELECT round($1::numeric, $2)::double precision $$;

-- ---------- Tablas ----------
-- id GENERATED BY DEFAULT: deja copiar los ids de SQLite tal cual (la copia
-- ajusta el contador al final).

CREATE TABLE IF NOT EXISTS drivers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  vehicle TEXT,
  pin TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'offline',
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  last_seen TEXT,
  paid_until TEXT,
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  vouched_by TEXT,
  vouched_at TEXT,
  deleted_at TEXT,
  tipo TEXT NOT NULL DEFAULT 'informal',
  accepted_legal_at TEXT,
  accepted_legal_version TEXT,
  photo TEXT,
  vehicle_type TEXT NOT NULL DEFAULT 'moto',
  cancel_count INTEGER NOT NULL DEFAULT 0,
  cooldown_until TEXT,
  grupo TEXT,
  signature TEXT,
  photo_placa TEXT,
  city TEXT NOT NULL DEFAULT 'tekax',
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  referred_by TEXT,
  photo_thumb TEXT,
  es_fundador INTEGER NOT NULL DEFAULT 0,
  deposit_bank TEXT,
  deposit_account TEXT,
  deposit_holder TEXT,
  es_prueba INTEGER NOT NULL DEFAULT 0,
  wants_rides INTEGER NOT NULL DEFAULT 0,
  wants_rides_at TEXT,
  invite_code TEXT,
  referred_by_driver_id INTEGER REFERENCES drivers(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_drivers_invite_code ON drivers(invite_code);

CREATE TABLE IF NOT EXISTS riders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT NOT NULL UNIQUE,
  name TEXT,
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  last_ride_at TEXT,
  city TEXT NOT NULL DEFAULT 'tekax',
  pin TEXT,
  no_show_count INTEGER NOT NULL DEFAULT 0,
  photo TEXT,
  home_lat DOUBLE PRECISION,
  home_lng DOUBLE PRECISION,
  home_label TEXT,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  photo_thumb TEXT,
  es_prueba INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_riders_pin ON riders(pin) WHERE pin IS NOT NULL;

CREATE TABLE IF NOT EXISTS rides (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_name TEXT NOT NULL,
  rider_phone TEXT NOT NULL,
  pickup_lat DOUBLE PRECISION NOT NULL,
  pickup_lng DOUBLE PRECISION NOT NULL,
  pickup_label TEXT,
  dest_lat DOUBLE PRECISION,
  dest_lng DOUBLE PRECISION,
  dest_label TEXT,
  passengers INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'buscando',
  driver_id INTEGER REFERENCES drivers(id),
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  updated_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  driver_disconnected_at TEXT,
  rating INTEGER,
  ride_type TEXT NOT NULL DEFAULT 'moto',
  cancelled_by TEXT,
  cancel_reason TEXT,
  rider_id INTEGER REFERENCES riders(id),
  fee_settled_at TEXT,
  children INTEGER NOT NULL DEFAULT 0,
  city TEXT NOT NULL DEFAULT 'tekax',
  service_kind TEXT NOT NULL DEFAULT 'pasaje',
  agreed_price DOUBLE PRECISION,
  share_token TEXT,
  deposit_amount DOUBLE PRECISION,
  deposit_status TEXT,
  deposit_bank TEXT,
  deposit_account TEXT,
  deposit_holder TEXT,
  deposit_receipt TEXT,
  deposit_receipt_at TEXT,
  deposit_confirmed_at TEXT,
  offer_price INTEGER,
  -- Milisegundos de Date.now(): no caben en INTEGER de Postgres.
  arrived_at_ms BIGINT,
  started_at_ms BIGINT,
  stop_wait_total_ms BIGINT,
  stop_wait_since_ms BIGINT,
  extra INTEGER NOT NULL DEFAULT 0,
  completed_at TEXT,
  driver_earnings DOUBLE PRECISION,
  for_name TEXT,
  for_note TEXT,
  business_id INTEGER,
  requested_from_km INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_rides_share_token ON rides(share_token) WHERE share_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_rides_business ON rides(business_id, created_at);
CREATE INDEX IF NOT EXISTS idx_rides_driver_status ON rides(driver_id, status);
CREATE INDEX IF NOT EXISTS idx_rides_rider_phone ON rides(rider_phone);
CREATE INDEX IF NOT EXISTS idx_rides_status ON rides(status);
-- Un chofer, un solo viaje activo. Con SQLite esto lo garantizaba que todo
-- corría en fila; con Postgres dos "aceptar" pueden llegar al mismo tiempo,
-- y este índice hace que el segundo falle (rides.js lo convierte en 409).
CREATE UNIQUE INDEX IF NOT EXISTS idx_rides_one_active_per_driver ON rides(driver_id)
  WHERE status IN ('aceptado', 'llegue', 'en_curso');

CREATE TABLE IF NOT EXISTS driver_applications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  photo TEXT,
  status TEXT NOT NULL DEFAULT 'pendiente',
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  accepted_legal_at TEXT,
  accepted_legal_version TEXT,
  vehicle_type TEXT NOT NULL DEFAULT 'moto',
  signature TEXT,
  grupo TEXT,
  tipo TEXT NOT NULL DEFAULT 'informal',
  photo_placa TEXT,
  city TEXT NOT NULL DEFAULT 'tekax',
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  referred_by TEXT,
  referred_by_driver_id INTEGER REFERENCES drivers(id)
);

CREATE TABLE IF NOT EXISTS driver_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id INTEGER NOT NULL REFERENCES drivers(id),
  amount DOUBLE PRECISION NOT NULL,
  period_start TEXT,
  period_end TEXT,
  paid_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  concept TEXT NOT NULL DEFAULT 'mensual',
  ride_count INTEGER,
  credit_applied DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS referral_rewards (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inviter_id INTEGER NOT NULL REFERENCES drivers(id),
  invitee_id INTEGER NOT NULL UNIQUE REFERENCES drivers(id),
  inviter_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  invitee_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  earned_at TEXT NOT NULL DEFAULT sl_datetime('now')
);

CREATE TABLE IF NOT EXISTS driver_credits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id INTEGER NOT NULL REFERENCES drivers(id),
  amount DOUBLE PRECISION NOT NULL,
  reason TEXT NOT NULL,
  reward_id INTEGER REFERENCES referral_rewards(id),
  created_at TEXT NOT NULL DEFAULT sl_datetime('now')
);
CREATE INDEX IF NOT EXISTS idx_driver_credits_driver ON driver_credits(driver_id);

CREATE TABLE IF NOT EXISTS driver_activity_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id INTEGER NOT NULL REFERENCES drivers(id),
  connected_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  disconnected_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_driver_activity_log_driver_id ON driver_activity_log(driver_id);

CREATE TABLE IF NOT EXISTS ride_offers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ride_id INTEGER NOT NULL REFERENCES rides(id),
  driver_id INTEGER NOT NULL REFERENCES drivers(id),
  price INTEGER NOT NULL,
  deposit_amount INTEGER,
  status TEXT NOT NULL DEFAULT 'pendiente',
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  responded_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_ride_offers_ride ON ride_offers(ride_id);
CREATE INDEX IF NOT EXISTS idx_ride_offers_driver ON ride_offers(driver_id, status);

CREATE TABLE IF NOT EXISTS ally_ads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city TEXT NOT NULL DEFAULT 'tekax',
  name TEXT NOT NULL,
  tagline TEXT,
  whatsapp TEXT NOT NULL,
  image TEXT,
  tier TEXT NOT NULL DEFAULT 'aliado',
  active INTEGER NOT NULL DEFAULT 1,
  starts_on TEXT,
  ends_on TEXT,
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  updated_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS ally_ad_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad_id INTEGER NOT NULL REFERENCES ally_ads(id),
  ride_id INTEGER NOT NULL REFERENCES rides(id),
  kind TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT sl_datetime('now')
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ally_ad_events_once ON ally_ad_events(ad_id, ride_id, kind);

CREATE TABLE IF NOT EXISTS ally_settings (
  city TEXT PRIMARY KEY,
  enabled INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS businesses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_id INTEGER NOT NULL UNIQUE REFERENCES riders(id),
  city TEXT NOT NULL DEFAULT 'tekax',
  name TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  address TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  updated_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  logo TEXT,
  cover TEXT,
  tagline TEXT,
  category TEXT,
  hours TEXT,
  whatsapp TEXT,
  is_open INTEGER NOT NULL DEFAULT 0,
  pay_bank TEXT,
  pay_account TEXT,
  pay_holder TEXT
);

CREATE TABLE IF NOT EXISTS menu_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id),
  category TEXT,
  name TEXT NOT NULL,
  description TEXT,
  price INTEGER NOT NULL,
  photo TEXT,
  available INTEGER NOT NULL DEFAULT 1,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  updated_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  deleted_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_menu_items_business ON menu_items(business_id);

CREATE TABLE IF NOT EXISTS food_settings (
  city TEXT PRIMARY KEY,
  enabled INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS family_settings (
  city TEXT PRIMARY KEY,
  enabled INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS push_keys (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  public_key TEXT NOT NULL,
  private_pem TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS driver_push_subs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id INTEGER NOT NULL REFERENCES drivers(id),
  endpoint TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  last_ok_at TEXT
);

CREATE TABLE IF NOT EXISTS rider_push_subs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ride_id INTEGER NOT NULL REFERENCES rides(id),
  endpoint TEXT NOT NULL,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT sl_datetime('now'),
  UNIQUE (ride_id, endpoint)
);

-- Milisegundos de Date.now() → BIGINT.
CREATE TABLE IF NOT EXISTS phone_otps (
  phone TEXT PRIMARY KEY,
  code_hash TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  last_sent_at BIGINT NOT NULL,
  window_start BIGINT NOT NULL,
  sends_in_window INTEGER NOT NULL DEFAULT 0
);

-- Del modelo de gremios (ya no se usa). Se copian para no perder historial.
CREATE TABLE IF NOT EXISTS leaders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  grupo TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT 'tekax',
  driver_count INTEGER NOT NULL DEFAULT 0,
  paid_until TEXT,
  notes TEXT,
  deleted_at TEXT,
  created_at TEXT NOT NULL DEFAULT sl_datetime('now')
);

CREATE TABLE IF NOT EXISTS leader_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leader_id INTEGER NOT NULL REFERENCES leaders(id),
  amount DOUBLE PRECISION NOT NULL,
  period_start TEXT,
  period_end TEXT,
  concept TEXT NOT NULL DEFAULT 'mensual',
  paid_at TEXT NOT NULL DEFAULT sl_datetime('now')
);

-- Sesiones del admin (6-oct-2026): se entra una vez con el PIN y el servidor
-- da un "pase" (token) que vence solo. Se guarda solo el sha256 del token,
-- nunca el token: si alguien copia la base, no le sirve para entrar.
CREATE TABLE IF NOT EXISTS admin_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL,
  created_ms BIGINT NOT NULL,
  last_seen_ms BIGINT NOT NULL,
  expires_ms BIGINT NOT NULL,
  ip TEXT,
  user_agent TEXT,
  revoked_at TEXT
);

-- Registro de movimientos del admin: quién hizo qué y cuándo (altas, bajas,
-- cobros, cambios de PIN, entradas). Nunca guarda PINs ni fotos.
CREATE TABLE IF NOT EXISTS admin_audit (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at TEXT NOT NULL DEFAULT sl_datetime('now'),
  role TEXT,
  zone TEXT,
  action TEXT NOT NULL,
  target_id INTEGER,
  detail TEXT,
  ip TEXT,
  ok INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_admin_audit_zone_at ON admin_audit(zone, at);

-- Entrar al admin con la huella del celular (passkey / WebAuthn). Aquí solo
-- queda la llave PÚBLICA de cada celular; la huella nunca sale del teléfono.
-- Cada llave es de un rol (tekax = dueño, progreso = Daniel...).
CREATE TABLE IF NOT EXISTS admin_passkeys (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  credential_id TEXT NOT NULL UNIQUE,
  public_key TEXT NOT NULL,
  counter BIGINT NOT NULL DEFAULT 0,
  transports TEXT,
  label TEXT,
  created_ms BIGINT NOT NULL,
  last_used_ms BIGINT
);
CREATE INDEX IF NOT EXISTS idx_admin_passkeys_role ON admin_passkeys(role);

-- Solicitudes de chofer (6-oct-2026): teléfono confirmado con código por
-- WhatsApp, y "rechazada" con su motivo cuando el admin contesta con amabilidad.
ALTER TABLE driver_applications ADD COLUMN IF NOT EXISTS phone_verified INTEGER NOT NULL DEFAULT 0;
ALTER TABLE driver_applications ADD COLUMN IF NOT EXISTS reject_reason TEXT;
